"""
Project Instructions Generator -- Creates .cortex/plan.md in the workspace.

Before the executor starts building, this module writes a structured instructions
file into the project workspace. The executor can reference it at any time to
stay aligned with the project roadmap.

This is the "baked in" instructions file that prevents blind building.

Contents:
- Project goal and success criteria
- Architecture decisions (made by the planner/Claude)
- Tech stack with specific versions
- File structure roadmap
- Phase breakdown
- Constraints and anti-patterns to avoid
- Build brief from Brain research (if available)

The file lives at .cortex/plan.md in the workspace root.
"""

import json
import os
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

INSTRUCTIONS_DIR = ".cortex"
INSTRUCTIONS_FILE = "plan.md"


def generate_project_instructions(
    plan: dict,
    goal: str,
    workspace_dir: str,
    brief: str = "",
    domain: str = "general",
    constraints: dict = None,
    research_context: str = "",
) -> str:
    """
    Generate .cortex/plan.md and write it to the workspace.
    
    Args:
        plan: The execution plan from the planner
        goal: Original project goal
        workspace_dir: Where to write the file
        brief: Build brief from Brain research
        domain: Target domain
        constraints: Tech stack / deploy constraints
        research_context: Raw research data from Brain
    
    Returns:
        Path to the created file
    """
    if not workspace_dir:
        return ""
    
    cortex_dir = os.path.join(workspace_dir, INSTRUCTIONS_DIR)
    os.makedirs(cortex_dir, exist_ok=True)
    filepath = os.path.join(cortex_dir, INSTRUCTIONS_FILE)
    
    # Build the markdown
    lines = []
    
    # Header
    lines.append("# Project Plan")
    lines.append("")
    lines.append(f"> Generated by Cortex on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"> Domain: {domain}")
    lines.append("")
    
    # Goal
    lines.append("## Goal")
    lines.append("")
    lines.append(goal)
    lines.append("")
    
    # Success Criteria
    if plan.get("success_criteria"):
        lines.append("## Success Criteria")
        lines.append("")
        lines.append(plan["success_criteria"])
        lines.append("")
    
    # Tech Stack
    if constraints and constraints.get("tech_stack"):
        lines.append("## Tech Stack")
        lines.append("")
        for tech in constraints["tech_stack"]:
            lines.append(f"- {tech}")
        lines.append("")
        if constraints.get("deploy_to"):
            lines.append(f"**Deploy to:** {constraints['deploy_to']}")
            lines.append("")
    
    # Architecture Decisions
    lines.append("## Architecture Decisions")
    lines.append("")
    lines.append("These decisions were made during planning. Do NOT change them during execution.")
    lines.append("")
    
    # Extract from plan metadata if available
    if plan.get("architecture_notes"):
        lines.append(plan["architecture_notes"])
    else:
        # Infer from plan steps
        lines.append("- **Routing:** Next.js App Router (src/app/)")
        lines.append("- **Styling:** Tailwind CSS + shadcn/ui components")
        lines.append("- **State:** React Server Components by default, `\"use client\"` only when needed")
        
        # Check plan for DB/auth decisions
        steps_text = json.dumps(plan.get("steps", []))
        if "supabase" in steps_text.lower():
            lines.append("- **Database:** Supabase (PostgreSQL)")
            lines.append("- **Auth:** Supabase Auth")
        elif "sqlite" in steps_text.lower() or "better-sqlite" in steps_text.lower():
            lines.append("- **Database:** better-sqlite3 (local)")
        elif "prisma" in steps_text.lower():
            lines.append("- **Database:** Prisma ORM")
        else:
            lines.append("- **Database:** None (static data / local JSON)")
        
        if "next-auth" in steps_text.lower() or "nextauth" in steps_text.lower():
            lines.append("- **Auth:** NextAuth.js v5")
        elif "clerk" in steps_text.lower():
            lines.append("- **Auth:** Clerk")
        elif "supabase" not in steps_text.lower():
            lines.append("- **Auth:** None")
    
    lines.append("")
    
    # Step-by-Step Roadmap
    steps = plan.get("steps", [])
    if steps:
        lines.append("## Execution Roadmap")
        lines.append("")
        lines.append("| Step | Tool | Description | Critical |")
        lines.append("|------|------|-------------|----------|")
        for s in steps:
            step_num = s.get("step", "?")
            tool = s.get("tool", "?")
            desc = s.get("description", "")[:80]
            crit = "Yes" if s.get("criticality", "required") == "required" else "No"
            lines.append(f"| {step_num} | {tool} | {desc} | {crit} |")
        lines.append("")
    
    # File Structure (planned)
    if plan.get("planned_files"):
        lines.append("## Planned File Structure")
        lines.append("")
        lines.append("```")
        for f in plan["planned_files"]:
            lines.append(f)
        lines.append("```")
        lines.append("")
    
    # Build Brief
    if brief:
        lines.append("## Build Brief (from Research)")
        lines.append("")
        lines.append(brief[:3000])
        lines.append("")
    
    # Constraints / Anti-Patterns
    lines.append("## Constraints")
    lines.append("")
    lines.append("- Do NOT use placeholder content (no `TODO`, `lorem ipsum`, `...`)")
    lines.append("- Do NOT change the tech stack mid-build")
    lines.append("- Do NOT skip error handling or TypeScript types")
    lines.append("- Do NOT install packages not in the plan without consulting the architect (_consult)")
    lines.append("- If something feels wrong, use `_consult` to ask the senior architect")
    lines.append("")
    
    # Communication Protocol
    lines.append("## Communication Protocol")
    lines.append("")
    lines.append("You have access to `_consult` -- a direct line to the senior architect (Claude).")
    lines.append("Use it when:")
    lines.append("- You face a design/architecture decision not covered in this plan")
    lines.append("- An error persists after one retry")
    lines.append("- You need to deviate from the plan")
    lines.append("- You're unsure about the right pattern for something")
    lines.append("")
    lines.append(f"Consultations remaining: 3 per execution run. Use them wisely.")
    lines.append("")
    
    content = "\n".join(lines)
    
    try:
        with open(filepath, "w") as f:
            f.write(content)
        logger.info(f"Project instructions written: {filepath} ({len(content)} chars)")
    except OSError as e:
        logger.error(f"Failed to write project instructions: {e}")
        return ""
    
    return filepath
